language: ruby
cache: bundler

rvm:
- 2.4.5
- 2.5.3
- 2.6.0

env:
  global:
    - CC_TEST_REPORTER_ID=bbc65a7f5858b221fbbb49617e4118dcce44703366ea64a49687214aed252cf3

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rake
  - bundle exec rubocop
  - bundle exec yard | if grep warn; then exit 1; else exit 0; fi

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
